#!/bin/bash

[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

~/.fehbg &
compton -b --config /dev/null &

# DWM Status Bar
while true
do
	BAT=$(battery)	
	LOCALTIME=$(date +"%I:%M %p")
	#TEMP="$(($(cat /sys/class/thermal/thermal_zone0/temp) / 1000))°C"

	xsetroot -name " $BAT $LOCALTIME "

	sleep 1m
done &

while true
do
    	/usr/local/bin/dwm 2> /dev/null
done
