#!/bin/sh

# Programs
alias vim="nvim"
alias v="nvim"
alias yt="youtube-dl --add-metadata -i"
alias yta="yt -x -f bestaudio/best"
alias ffmpeg="ffmpeg -hide_banner"

# General
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -v"
alias mkd="mkdir -pv"

# Colors
alias ls="ls -hN --color=auto --group-directories-first" 
alias grep="grep --color=auto" 
alias diff="diff --color=auto"
