#!/bin/sh

# Programs
alias vim="nvim"
alias v="nvim"
alias yt="youtube-dl --add-metadata -i"
alias yta="yt -x -f bestaudio/best"
alias ffmpeg="ffmpeg -hide_banner"

# General
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -v"
alias mkd="mkdir -pv"

# Colors
alias ls="ls -hN --color=auto --group-directories-first" 
alias grep="grep --color=auto" 
alias diff="diff --color=auto" 
alias cmatrix="cmatrix -C blue"

# Configs
alias zshrc="nvim ~/.config/zsh/.zshrc"
alias spectrwm="nvim ~/.spectrwm.conf"
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'

# Git
alias gc="git add . && git commit"
alias gcp="gc && git push"

# Custom
alias golfo="fortune | cowsay -f tux | lolcat"
