#!/bin/sh

# Programs
alias vim="nvim"
alias v="nvim"
alias yt="youtube-dl --add-metadata -i"
alias yta="yt -x -f bestaudio/best"
alias ffmpeg="ffmpeg -hide_banner"

# Calculator with math support
alias bc="bc -l"

# General
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -v"
alias mkd="mkdir -pv"

# Pretty
alias ls="ls -hN --color=auto --group-directories-first"
alias grep="grep --color=auto"
alias egrep='egrep --color=auto'
alias fgrep="fgrep --color=auto"
alias diff="diff --color=auto"
alias mount="mount |column -t"
alias tree="tree -C"

# Git
alias gitprune="git branch -r | awk '{print $1}' | egrep -v -f /dev/fd/0 <(git branch -vv | grep origin) | awk '{print $1}' | xargs git branch -d"

# ASDF
alias update-nvim-nightly="asdf uninstall neovim nightly && asdf install neovim nightly"
