#!/bin/sh

# Programs
alias yt="youtube-dl --add-metadata -i"
alias yta="yt -x -f bestaudio/best"
alias ffmpeg="ffmpeg -hide_banner"

# General
alias mkd="mkdir -pv"

# Pretty
alias grep="grep --color=auto"
alias egrep='egrep --color=auto'
alias fgrep="fgrep --color=auto"
alias diff="diff --color=auto"
alias mount="mount |column -t"
alias tree="tree -C"

# Git
alias gitprune="git branch -r | awk '{print $1}' | egrep -v -f /dev/fd/0 <(git branch -vv | grep origin) | awk '{print $1}' | xargs git branch -d"

# Yubikey
alias yubikey-sync="gpg-connect-agent 'scd serialno' 'learn --force' /bye"
